spring:
  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3305/store?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true